[phases.setup]
nixPkgs = ['...', 'chromium']

[phases.install]
cmds = ['npm install']

[phases.build]
cmds = ['npx prisma generate', 'npm run build']

[start]
cmd = 'npx prisma migrate deploy && npm run seed:production && node dist/index.js'
